page_title: "AI Affiliate Launchpad â€“ InsightfulAffiliate"
page_description: "Build your first affiliate funnel in 60 minutes with friendly, no-hype guidance."
canonical_url: "https://www.insightfulaffiliate.com/opt-in"
site_name: "InsightfulAffiliate"
brand_name: "InsightfulAffiliate"
brand_alt_name: "NextGenCopyAI"
brand_website: "https://www.insightfulaffiliate.com/"
logo_url: "https://d1yei2z3i6k35z.cloudfront.net/13254463/68bc0bd21be8b_InsightfulAffiliate_horizontal_transparent_dark-fg_640w.png"
og_image_url: "https://d1yei2z3i6k35z.cloudfront.net/13254463/68c25df1dc6f4_InsightfulAffiliate_og_light_1200x630.png"
twitter_image_url: "https://d1yei2z3i6k35z.cloudfront.net/13254463/68c25df1dd6c4_InsightfulAffiliate_twitter_light_1200x628.png"
favicon_ico_url: "https://d1yei2z3i6k35z.cloudfront.net/13254463/68c13281652cd_favicon_light.ico"
apple_touch_icon_url: "https://d1yei2z3i6k35z.cloudfront.net/13254463/68b2b075f0945_apple-touch-icon.png"
manifest_url: "<ADD_IA_MANIFEST_URL_HERE>"
ngcai_css_url: "https://d1yei2z3i6k35z.cloudfront.net/13254463/68f2fb38333dd_ngcai.css"
override_css_url: "<UPLOAD_IA_OVERRIDE_CSS_AND_PASTE_URL_HERE>"
cdn_domain: "https://d1yei2z3i6k35z.cloudfront.net"
twitter_url: "https://twitter.com/InsightfulAF"
facebook_url: "https://facebook.com/profile.php?id=61580983854074"
linkedin_url: "https://linkedin.com/in/insightfulaffiliate"
