page_title: "NextGenCopyAI â€“ AI Affiliate Launchpad"
page_description: "Modern copy and tools to launch funnels quickly and cleanly."
canonical_url: "https://www.nextgencopyai.com/opt-in"
site_name: "NextGenCopyAI"
brand_name: "NextGenCopyAI"
brand_alt_name: "InsightfulAffiliate"
brand_website: "https://www.nextgencopyai.com/"
logo_url: "https://d1yei2z3i6k35z.cloudfront.net/13254463/68bc0bd222e38_NextGenCopyAI_horizontal_transparent_dark-fg_640w.png"
og_image_url: "https://d1yei2z3i6k35z.cloudfront.net/13254463/68ce610b1fb2d_og-default.png"
twitter_image_url: "https://d1yei2z3i6k35z.cloudfront.net/13254463/68ce61326564f_twitter-default.png"
favicon_ico_url: "https://d1yei2z3i6k35z.cloudfront.net/13254463/68b7b43c6aa85_favicon.ico"
apple_touch_icon_url: "https://d1yei2z3i6k35z.cloudfront.net/13254463/68b2b075f0945_apple-touch-icon.png"
manifest_url: "<ADD_NGCAI_MANIFEST_URL_HERE>"
ngcai_css_url: "https://d1yei2z3i6k35z.cloudfront.net/13254463/68f2fb38333dd_ngcai.css"
override_css_url: "<UPLOAD_NGCAI_OVERRIDE_CSS_AND_PASTE_URL_HERE>"
cdn_domain: "https://d1yei2z3i6k35z.cloudfront.net"
twitter_url: "https://twitter.com/InsightfulAF"
facebook_url: "https://facebook.com/profile.php?id=61580983854074"
linkedin_url: "https://linkedin.com/in/insightfulaffiliate"
